### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by GadgetGeekUK** [bobbydharrell/StepController#1]
How can I bind 'Steps'? 

If you declaratively define steps in the xaml - they are not appearing - the example code where main populates the steps works.

I'm trying to set the bar as a ListItem template, bound to a view model where each item in the list has an Observable<Step> collection, and a property indicating the progress.

Could you provide an item template binding example?

Many thanks!!

**Comment by bobbydharrell** [comment]
Hi Mel,

This control was originally written for WPF, not Xamarin, and is outdated.

Please see this alternative I found on the web:
https://xamgirl.com/step-bar-in-xamarin-forms/

Sincerely,
Bobby Harrell
B-Tech Labs, LLC
***@***.***
http://www.b-techlabs.com

**Comment by GadgetGeekUK** [comment]
Yes, it's WPF I'm after! - Love those long living legacy Windows apps!
I'm making progress with it. Managed to get each instance in the item template to show a predefined list of steps on first render. Still need to then update the IsComplete based on the instance item data.

**Comment by GadgetGeekUK** [comment]
Resolved it in the end. A fair few modifications to allow the binding events to occur with the correct data at the correct time...

**Comment by bobbydharrell** [comment]
Awesome! Glad you got it working!!
________________________________
